### ISSUE TITLE
npm install error

### ISSUE THREAD

**Issue by yaxionglin** [amida-tech/blue-button#273]
npm install hung:
> npm install @amida-tech/blue-button
(##################) ⠙ reify:@amida-tech/blue-button: timing reifyNode:node_modules/moment Completed in 1861ms
(##################) ⠙ reify:@amida-tech/blue-button: timing reifyNode:node_modules/moment Completed in 1861ms
(##################) ⠙ reify:@amida-tech/blue-button: timing reifyNode:node_modules/moment Completed in 1861ms
(##################) ⠙ reify:@amida-tech/blue-button: timing reifyNode:node_modules/moment Completed in 1861ms

The install log file shows lots of errors, see below.

I have tried all versions: 1.10.4 - 1.10.9, all have the same problem.  Any idea what might be causing this error and how to fix it?

Thanks.

...
421 timing auditReport:init Completed in 0ms
422 timing reify:audit Completed in 4718ms
423 info run @manhydra/libxmljs@0.19.12 install { code: null, signal: 'SIGINT' }
424 timing reify:rollback:createSparse Completed in 543ms
425 timing reify:rollback:retireShallow Completed in 1ms
426 timing command:install Completed in 69544ms
427 verbose stack Error: command failed
427 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/@npmcli/promise-spawn/lib/index.js:53:27)
427 verbose stack     at ChildProcess.emit (node:events:512:28)
427 verbose stack     at maybeClose (node:internal/child_process:1098:16)
427 verbose stack     at Socket.<anonymous> (node:internal/child_process:456:11)
427 verbose stack     at Socket.emit (node:events:512:28)
427 verbose stack     at Pipe.<anonymous> (node:net:316:12)
428 verbose pkgid @manhydra/libxmljs@0.19.12
429 verbose cwd /Users/yxl01/temp/care-everywhere
430 verbose Darwin 20.6.0
431 verbose node v19.6.0
432 verbose npm  v9.4.0
433 error path /Users/yxl01/temp/care-everywhere/node_modules/@manhydra/libxmljs
434 error command failed
435 error signal SIGINT
436 error command sh -c node-pre-gyp install --fallback-to-build --loglevel http
437 error CXX(target) Release/obj.target/xmljs/src/libxmljs.o
437 error   CXX(target) Release/obj.target/xmljs/src/xml_attribute.o
437 error   CXX(target) Release/obj.target/xmljs/src/xml_document.o
437 error   CXX(target) Release/obj.target/xmljs/src/xml_element.o
437 error   CXX(target) Release/obj.target/xmljs/src/xml_comment.o
437 error   CXX(target) Release/obj.target/xmljs/src/xml_namespace.o
437 error   CXX(target) Release/obj.target/xmljs/src/xml_node.o
437 error   CXX(target) Release/obj.target/xmljs/src/xml_sax_parser.o
437 error   CXX(target) Release/obj.target/xmljs/src/xml_syntax_error.o
437 error   CXX(target) Release/obj.target/xmljs/src/xml_text.o
437 error   CXX(target) Release/obj.target/xmljs/src/xml_pi.o
437 error   CXX(target) Release/obj.target/xmljs/src/xml_xpath_context.o
437 error   CC(target) Release/obj.target/xmljs/vendor/libxml/buf.o
437 error   CC(target) Release/obj.target/xmljs/vendor/libxml/catalog.o
437 error   CC(target) Release/obj.target/xmljs/vendor/libxml/chvalid.o
437 error   CC(target) Release/obj.target/xmljs/vendor/libxml/dict.o
437 error   CC(target) Release/obj.target/xmljs/vendor/libxml/encoding.o
437 error   CC(target) Release/obj.target/xmljs/vendor/libxml/entities.o
437 error   CC(target) Release/obj.target/xmljs/vendor/libxml/error.o
437 error   CC(target) Release/obj.target/xmljs/vendor/libxml/globals.o
437 error   CC(target) Release/obj.target/xmljs/vendor/libxml/hash.o
437 error   CC(target) Release/obj.target/xmljs/vendor/libxml/HTMLparser.o
437 error   CC(target) Release/obj.target/xmljs/vendor/libxml/HTMLtree.o
437 error   CC(target) Release/obj.target/xmljs/vendor/libxml/legacy.o
437 error   CC(target) Release/obj.target/xmljs/vendor/libxml/list.o
437 error   CC(target) Release/obj.target/xmljs/vendor/libxml/parser.o
437 error   CC(target) Release/obj.target/xmljs/vendor/libxml/parserInternals.o
437 error   CC(target) Release/obj.target/xmljs/vendor/libxml/pattern.o
437 error   CC(target) Release/obj.target/xmljs/vendor/libxml/relaxng.o
437 error   CC(target) Release/obj.target/xmljs/vendor/libxml/SAX2.o
437 error   CC(target) Release/obj.target/xmljs/vendor/libxml/SAX.o
437 error   CC(target) Release/obj.target/xmljs/vendor/libxml/tree.o
437 error   CC(target) Release/obj.target/xmljs/vendor/libxml/threads.o
437 error   CC(target) Release/obj.target/xmljs/vendor/libxml/uri.o
437 error   CC(target) Release/obj.target/xmljs/vendor/libxml/valid.o
437 error   CC(target) Release/obj.target/xmljs/vendor/libxml/xinclude.o
437 error   CC(target) Release/obj.target/xmljs/vendor/libxml/xlink.o
437 error   CC(target) Release/obj.target/xmljs/vendor/libxml/xmlIO.o
437 error   CC(target) Release/obj.target/xmljs/vendor/libxml/xmlmemory.o
437 error   CC(target) Release/obj.target/xmljs/vendor/libxml/xmlmodule.o
437 error   CC(target) Release/obj.target/xmljs/vendor/libxml/xmlreader.o
437 error   CC(target) Release/obj.target/xmljs/vendor/libxml/xmlregexp.o
437 error   CC(target) Release/obj.target/xmljs/vendor/libxml/xmlsave.o
437 error   CC(target) Release/obj.target/xmljs/vendor/libxml/xmlschemas.o
438 error node-pre-gyp http GET https://github.com/libxmljs/libxmljs/releases/download/v0.19.12/node-v111-darwin-x64.tar.gz
438 error node-pre-gyp WARN Pre-built binaries not installable for @manhydra/libxmljs@0.19.12 and node@19.6.0 (node-v111 ABI, unknown) (falling back to source compile with node-gyp) 
438 error node-pre-gyp WARN Hit error fetch is not a function 
438 error gyp info it worked if it ends with ok
438 error gyp info using node-gyp@9.3.0
438 error gyp info using node@19.6.0 | darwin | x64
438 error gyp info ok 
438 error gyp http GET https://nodejs.org/download/release/v19.6.0/node-v19.6.0-headers.tar.gz
438 error gyp http 200 https://nodejs.org/download/release/v19.6.0/node-v19.6.0-headers.tar.gz
438 error gyp http GET https://nodejs.org/download/release/v19.6.0/SHASUMS256.txt
438 error gyp http 200 https://nodejs.org/download/release/v19.6.0/SHASUMS256.txt
438 error ../src/xml_sax_parser.cc:130:10: warning: 'MakeCallback' is deprecated [-Wdeprecated-declarations]
438 error     Nan::MakeCallback(this->handle(), v8::Local<v8::Function>::Cast(emit_v), argc + 1, args);
438 error          ^
438 error ../../../nan/nan.h:1030:3: note: 'MakeCallback' has been explicitly marked deprecated here
438 error   NAN_DEPRECATED inline v8::Local<v8::Value> MakeCallback(
438 error   ^
438 error ../../../nan/nan.h:110:40: note: expanded from macro 'NAN_DEPRECATED'
438 error # define NAN_DEPRECATED __attribute__((deprecated))
438 error                                        ^
438 error 1 warning generated.
438 error make: *** [Release/obj.target/xmljs/vendor/libxml/xmlschemas.o] Interrupt: 2
439 verbose exit 1
440 timing npm Completed in 69610ms
441 verbose unfinished npm timer reify 1675442071367
442 verbose unfinished npm timer reify:build 1675442079463
443 verbose unfinished npm timer build 1675442079464
444 verbose unfinished npm timer build:deps 1675442079465
445 verbose unfinished npm timer build:run:install 1675442079476
446 verbose unfinished npm timer build:run:install:node_modules/@manhydra/libxmljs 1675442079477
447 verbose code 1
448 error A complete log of this run can be found in:
448 error     /Users/yxl01/.npm/_logs/2023-02-03T16_34_31_305Z-debug-0.log

**Comment by yaxionglin** [comment]
Forgot to include the OS info:

Mac BigSur ver 11.7.2
Node: latest 19.6.0
npm: 9.4.0


Also tried on Docker and it failed too:

npm ERR! gyp ERR! find Python - Use the switch --python="/path/to/pythonexecutable"
npm ERR! gyp ERR! find Python   (accepted by both node-gyp and npm)
npm ERR! gyp ERR! find Python - Set the environment variable PYTHON
npm ERR! gyp ERR! find Python - Set the npm configuration variable python:
npm ERR! gyp ERR! find Python   npm config set python "/path/to/pythonexecutable"
npm ERR! gyp ERR! find Python For more information consult the documentation at:
npm ERR! gyp ERR! find Python https://github.com/nodejs/node-gyp#installation
npm ERR! gyp ERR! find Python **********************************************************
npm ERR! gyp ERR! find Python 
npm ERR! gyp ERR! configure error 
npm ERR! gyp ERR! stack Error: Could not find any Python installation to use
npm ERR! gyp ERR! stack     at PythonFinder.fail (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/find-python.js:330:47)
npm ERR! gyp ERR! stack     at PythonFinder.runChecks (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/find-python.js:159:21)
npm ERR! gyp ERR! stack     at PythonFinder.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/find-python.js:202:16)
npm ERR! gyp ERR! stack     at PythonFinder.execFileCallback (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/find-python.js:294:16)
npm ERR! gyp ERR! stack     at exithandler (node:child_process:404:5)
npm ERR! gyp ERR! stack     at ChildProcess.errorhandler (node:child_process:416:5)
npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:390:28)
npm ERR! gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:288:12)
npm ERR! gyp ERR! stack     at onErrorNT (node:internal/child_process:477:16)
npm ERR! gyp ERR! stack     at processTicksAndRejections (node:internal/process/task_queues:83:21)
npm ERR! gyp ERR! System Linux 5.4.0-1037-gcp
npm ERR! gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--loglevel=http" "--module=/node_modules/@manhydra/libxmljs/build/Release/xmljs.node" "--module_name=xmljs" "--module_path=/node_modules/@manhydra/libxmljs/build/Release" "--napi_version=8" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v93"
npm ERR! gyp ERR! cwd /node_modules/@manhydra/libxmljs
npm ERR! gyp ERR! node -v v16.13.2
npm ERR! gyp ERR! node-gyp -v v8.3.0
npm ERR! gyp ERR! not ok 
npm ERR! node-pre-gyp ERR! build error 
npm ERR! node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --loglevel=http --module=/node_modules/@manhydra/libxmljs/build/Release/xmljs.node --module_name=xmljs --module_path=/node_modules/@manhydra/libxmljs/build/Release --napi_version=8 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v93' (1)
npm ERR! node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/node_modules/@manhydra/node-pre-gyp/lib/util/compile.js:89:23)
npm ERR! node-pre-gyp ERR! stack     at ChildProcess.emit (node:events:390:28)
npm ERR! node-pre-gyp ERR! stack     at maybeClose (node:internal/child_process:1064:16)
npm ERR! node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5)
npm ERR! node-pre-gyp ERR! System Linux 5.4.0-1037-gcp
npm ERR! node-pre-gyp ERR! command "/usr/local/bin/node" "/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build" "--loglevel" "http"
npm ERR! node-pre-gyp ERR! cwd /node_modules/@manhydra/libxmljs
npm ERR! node-pre-gyp ERR! node -v v16.13.2
npm ERR! node-pre-gyp ERR! node-pre-gyp -v v1.0.10
npm ERR! node-pre-gyp ERR! not ok

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2023-02-03T16_38_48_496Z-debug.log
The command '/bin/sh -c npm install' returned a non-zero code: 1

**Comment by Manhydra** [comment]
On your Mac BigSur ver 11.7.2, what version of Python is installed?
